Сделал задание
htmlacademy-htmlcss/2149063-device-35 pull request #2
Opened 2022-09-26 14:21 UTC by TyaVa5

2022-09-27 12:28 UTC, avylando requested changes
Привет! Поправь, пожалуйста все замечания

Кроме того, не забывай проверять документ в [валидаторе](https://validator.w3.org/nu/#textarea), с ним уже многие ошибки можно было бы избежать

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +
Поиск нужно сделать формой (form) с вложенным инпутом (input) и кнопкой Найти (button type="submit")

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +
На странице каталога нужно сверстать состояние с залогиненным пользователем - как на макете
<img width="144" alt="Снимок экрана 2022-09-27 в 13 46 29" src="https://user-images.githubusercontent.com/30809044/192506091-ae73eb0b-8c6c-45d4-a6a1-a6e74a711c52.png">

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +    <h1> <span class="visually-hidden">
Видимые элементы не нужно делать с классом `visually-hidden`
оставь просто заголовок с текстом

```
<h1>Device</h1>

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +          <span class="visually-hidden">
тут и ниже тоже везде убрать класс `visually-hidden` для тех элементов, где текст видимый

Этот класс нужно использовать только для невидимых подписей к интерактивным элементам, когда у них нет видимого текста, например когда есть кликабельная иконка соцсетей и ее требуется подписать

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +        <a class="navigation-link" href="shopping cart">
ссылки должны вести на html-страницу, если их адрес известен
для всех остальных ссылок используй `href="#"`
поправь везде, в соответствии с критерием

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +        <a class="navigation-link" href="Catalog">
тут ссылка должна быть на `catalog.html` либо вообще убрать атрибут `href`, т.к. мы уже находимся на странице каталога (см критерий https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03)

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +        <h1 class="inner-header-title">Моноподы для селфи</h1>
h1 должен быть только один на странице и он у тебя уже есть в шапке (Device)

этот заголовок уже делай вторым уровнем (h2)

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +      <fieldset class="catalog-filter-group">
fieldset должен находиться внутри form http://htmlbook.ru/html/fieldset

Форма должна быть работоспособной, чтобы можно было отправить данные по клику на кнопку Показать

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03
https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-04

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +        </label>
Чекбоксы одной группы должны быть объединены одинаковым `name`, а отличаться атрибутом `value`

пример

```
        <label class="control">
          <input class="control-input" type="checkbox" name="color" value="black" checked>
          Черный
        </label>
        <label class="control">
          <input class="control-input" type="checkbox" name="color" value="white" checked>
          Белый
        </label>
        <label class="control">
          <input class="control-input" type="checkbox" name="color" value="blue">
          Синий
        </label>
        <label class="control">
          <input class="control-input" type="checkbox" name="color" value="red">
          Красный
        </label>
        <label class="control">
          <input class="control-input" type="checkbox" name="color" value="pink">
          Розовый
        </label>
```

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +        Нет
Это не чекбоксы, а радиобаттоны (`type="radio"`) - выбор одного варианта из нескольких

Они тоже должны быть сгруппированы под одним `name` чтобы корректно переключаться 
```
      <label class="control">
        <input class="control-input" type="radio" name="bluetooth" value="on" checked>
        Есть
      </label>
      <label class="control">
        <input class="control-input" type="radio" name="bluetooth" value="off">
        Нет
</label>
```

Кроме того, атрибут `checked` нужно писать с маленькой буквы, как и все атрибуты

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +      <b class="product-card-price">500 ₽</b>
Цену лучше тоже сразу обернуть в ссылку, так как вся карточка будет ссылкой на страницу товара

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +        <img class="product-card-image" src="" alt="">
Нужно указать `alt` у всех изображений

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +    <div class="product-card">
Список товаров рекомендую сверстать списком `ul`

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +        <a class="pagination-link pagination-prev pagination-disabled">
не забывай атрибут `href="#"` у ссылок

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +  <section class="page-footer">
Этот section лишний, тк он лишь оборачивает `footer`, который сам по себе уже является секцией

2022-09-27 12:28 UTC, avylando commented on catalog.html
> +                <a class="button" href="#">
ссылки на соцсети нужно проставить, они есть в требованиях к макету https://www.figma.com/file/B2S5PupxHYVFbrWD9CWZgp/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=308%3A470

2022-09-27 12:28 UTC, avylando commented on index.html
> +     </H1>
То же самое что и в каталоге, h1 может использоваться только один раз на странице, тут нужно сделать h2

2022-09-27 12:28 UTC, avylando commented on index.html
> +      <p class="visually-hidden">Этот обычный, на первый взгляд, квадрокоптер оснащен мощным лазером, замаскированным под стандартную камеру.
это не скрытый элемент, тут также нужно везде убрать `visually-hidden`

2022-09-27 12:28 UTC, avylando commented on index.html
> +      <img class="quadrocopters" src="" alt="Квадрокоптеры">
советую сделать это списком `ul`

также тут кроме картинок должна быть подпись текстом и все это нужно обернуть в ссылку

2022-09-27 12:28 UTC, avylando commented on index.html
> +  <ul class="Information">
классы называй всегда с маленькой буквы
здесь логично назвать элемент `information-list`

2022-09-27 12:28 UTC, avylando commented on index.html
> +            Гарантия</span>
тут забыл закрывающий тег `</a>`

2022-09-27 12:28 UTC, avylando commented on index.html
> +                </a>
Тут нужно сверстать все слайды, как на стайлгайде https://www.figma.com/file/B2S5PupxHYVFbrWD9CWZgp/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=11558%3A5700

Также лучше все сделать одним списком

И тут `</a>` как раз нашелся) перенеси его выше, куда я написал

2022-09-27 12:28 UTC, avylando commented on index.html
> +        <a class="information-link" href="Warranty">
`href="#"` тут и везде, где нет известной страницы

2022-09-27 12:28 UTC, avylando commented on index.html
> +  <h1 class="about-us-title"> О нас</h1>
h2

2022-09-27 12:28 UTC, avylando commented on index.html
> +  <a class="about-description">
Тут не должно быть ссылки, используй div

2022-09-27 12:28 UTC, avylando commented on index.html
> +          <b> Меловые линии</b>
Не забывай закрывающие теги

2022-09-27 12:28 UTC, avylando commented on index.html
> +                  </ul>
Тут список из одного элемента выглядит странно, можешь просто обернуть в div

2022-09-27 12:28 UTC, avylando commented on index.html
> +<section class="Contacts">
старайся использовать только строчные буквы в именах классов, атрибутов

2022-09-27 12:28 UTC, avylando commented on index.html
> +  <a class="contacts-description">
Не нужно использовать ссылки как обертку, используй div в таких случаях

2022-09-27 12:28 UTC, avylando commented on index.html
> +  <section class="page-footer">
Лишняя секция

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +      <img class="vxod-profile" src="" alt="Коля Петухов">
Тут нужно обернуть картинку в `li`, так как прямыми потомками `ul` могут быть только элементы `li`

Также нужно добавить текст рядом с картинкой, alt тут не соответсвует картинке

У img нужно добавить закрывающий слэш

Кроме того, именование транслитом запрещено https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-02

В итоге, должно быть примерно так 

```
<li>
  <img class="navigation-profile-icon" src="" alt="Профиль" />
  <span>Коля Петухов</span>
</li>
```

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +            Выйти</span>
Тут visually-hidden не убрал

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +        <h1 class="inner-header-title">Моноподы для селфи</h1>
не исправлено

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +          <a class="breadcrumbs-link" href="#">Главная</a>
тут зря ссылку убрал

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +        <img class="product-card-image" src="" alt="">
Не исправлено

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +      <b class="product-card-price">500 ₽</b>
Не исправлено

2022-09-30 10:21 UTC, avylando commented on index.html
> +      <p class="visually-hidden">Этот обычный, на первый взгляд, квадрокоптер оснащен мощным лазером, замаскированным под стандартную камеру.
Не исправлено

2022-09-30 10:21 UTC, avylando commented on index.html
> +     <div class="catalog">
Тут надо было оставить `section`

2022-09-30 10:21 UTC, avylando commented on index.html
> +        <a class="information-link" href="Warranty">
Не исправлено

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +        <input type="submit" value="Найти">
form с инпутами нельзя вкладывать в ссылку, тут нужно убрать navigation-link (тем более у него нет закрывающего тега - из-за этого валидатор ругается) и оставить только форму

2022-09-30 10:21 UTC, avylando commented on catalog.html
> +        <input type="submit" value="Найти">
`input` нужно делать самозакрывающимся тегом, добавь слэш в конце

<input type="search" value="Текст поиска"**/**>
<input type="submit" value="Найти"**/**>

2022-09-30 10:21 UTC, avylando commented on index.html
>    </a>
Тут забыл убрать закрывающий тег 
Будь внимательней с порядком открытия/закрытия тегов, у тебя из-за этого в основном ошибки в валидаторе

2022-10-06 10:45 UTC, avylando requested changes
Привет! Все еще много проблем с версткой, некоторые замечания не исправлены
Кроме того, в валидаторе много ошибок - их обязательно нужно править

2022-10-06 10:45 UTC, avylando commented on catalog.html
> +    <input type="submit" value="Найти"/>
Это все нужно обернуть в form

2022-10-06 10:45 UTC, avylando commented on index.html
> +  <h1 class="about-us-title"> О нас</h1>
не исправил

2022-10-06 10:45 UTC, avylando commented on catalog.html
> +      <b class="product-card-price">500 ₽</b>
Не исправлено

2022-10-06 10:45 UTC, avylando commented on index.html
> +    </h1>
h1 у тебя уже есть выше, это уже h2
Я писал это еще в первом ревью, внимательно просмотри все замечания
С валидатором у тебя по-прежнему проблемы

2022-10-06 10:45 UTC, avylando commented on index.html
> +
Всю разметку нужно делать внутри body

2022-10-06 10:45 UTC, avylando commented on index.html
> +        <a class="information-link" href="Warranty">
не исправлено

2022-10-06 10:45 UTC, avylando commented on index.html
> +  <ul class="Information">
не исправлено

2022-10-16 14:27 UTC, TyaVa5 commented
все

2022-10-17 14:14 UTC, avylando requested changes
Привет! К сожалению, замечаний еще многовато, не могу пока принять
Зарезолвил те комментарии, которые ты поправил, пройдись пожалуйста внимательно по всем оставшимся и поправь

2022-10-17 14:14 UTC, avylando commented on catalog.html
> +    </form>
Для этой кнопки не нужно делать отдельную форму, нужно ее поместить в форму с фильтрами

2022-10-17 14:14 UTC, avylando commented on index.html
> +        <a class="navigation-link" href="Login">
href еще не везде исправил

2022-10-17 14:14 UTC, avylando commented on catalog.html
> +<span>Коля Петухов</span>
Это нужно обернуть в ссылку

2022-10-17 14:14 UTC, avylando commented on catalog.html
> +        <a class="navigation-link" href="Login">
href везде поправить

2022-10-17 14:14 UTC, avylando commented on catalog.html
> +    <form>
Не нужно разбивать одну форму на несколько, все эти элементы должны быть в одном теге form

2022-10-17 14:14 UTC, avylando commented on index.html
> +     <section class="description">
тут section вклинивается между элементами слайда, поправь - слайдер весь должен быть обернут в секцию

2022-10-17 14:14 UTC, avylando commented on index.html
> +       <section class="description">
Все понятно) Это не section, а div - поправь везде в слайдах
И не забывай оборачивать в section, у тебя сейчас список со слайдами не принадлежит ни к какой секции

2022-10-17 14:14 UTC, avylando commented on index.html
> +        <img class="virtual-reality" src="#" alt="Виртуальная реальность">
Тут у везде в элементах списка не хватает подзаголовка

2022-10-17 14:14 UTC, avylando commented on index.html
> +          <span class="visually-hidden">
visually-hidden тут и в других слайдах убрать - заголовок должен быть видимым

2022-10-17 14:14 UTC, avylando commented on index.html
> +              <h2 class="visually-hidden">
здесь тоже, и везде еще раз проверь пожалуйста - если ты видишь на макете надпись - то она не может быть `visually-hidden`

2022-10-17 14:14 UTC, avylando commented on catalog.html
> +          <span>
span тут уже не нужен

2022-10-20 15:17 UTC, avylando reviewed
Привет! Задание принял, нужно двигаться дальше
Кое-где перестарался с href, верни пожалуйста телефоны) У же в рамках следующего задания

2022-10-20 15:17 UTC, avylando commented on catalog.html
> +  <a>
href не забудь

2022-10-20 15:17 UTC, avylando commented on catalog.html
> +                <a class="footer-contacts-address-phone" href="#">Тел.: +7 (812) 812-12-12</a>
тут верни tel, зря убрал

2022-10-20 15:17 UTC, avylando commented on index.html
> +      <a class="contacts-phone" href="#">+7 (812) 812-12-12</a>
Тут тоже верни значение href, для телефонов у тебя все правильно было

2022-10-20 15:17 UTC, avylando commented on index.html
> +                  <a class="footer-contacts-address-phone" href="#">Тел.: +7 (812) 812-12-12</a>
и тут верни

2022-10-20 15:17 UTC, merged